export const CONNECT_CHAT_SUCCESS = 'CONNECT_CHAT_SUCCESS';
export const CONNECT_CHAT_FAILURE = 'CONNECT_CHAT_FAILURE';

export const DISCONNECT_CHAT_SUCCESS = 'DISCONNECT_CHAT_SUCCESS';
export const RECONNECT_CHAT_SUCCESS = 'RECONNECT_CHAT_SUCCESS';

export const MATCH_PARTNER_PENDING = 'MATCH_PARTNER_PENDING';
export const MATCH_PARTNER_SUCCESS = 'MATCH_PARTNER_SUCCESS';
export const MATCH_PARTNER_RESTART = 'MATCH_PARTNER_RESTART';

export const SEND_NEW_TEXT_SUCCESS = 'SEND_NEW_TEXT_SUCCESS';
export const CLEAR_CHAT_TEXTS = 'CLEAR_CHAT_TEXTS';

export const START_TYPING = 'START_TYPING';
export const STOP_TYPING = 'STOP_TYPING';
