export const ENTER_NEW_ROOM_SUCCESS = 'ENTER_NEW_ROOM_SUCCESS';
export const ENTER_NEW_ROOM_FAILURE = 'ENTER_NEW_ROOM_FAILURE';

export const MATCH_PARTNER_PENDING = 'MATCH_PARTNER_PENDING';
export const MATCH_PARTNER_SUCCESS = 'MATCH_PARTNER_SUCCESS';
export const MATCH_PARTNER_RESTART = 'MATCH_PARTNER_RESTART';
export const MATCH_PARTNER_FAILURE = 'MATCH_PARTNER_FAILURE';

export const PARTNER_DISCONNECTION_SUCCESS = 'PARTNER_DISCONNECTION_SUCCESS';
export const PARTNER_DISCONNECTION_CANCEL = 'PARTNER_DISCONNECTION_CANCEL';
export const PARTNER_DISCONNECTION_FAILURE = 'PARTNER_DISCONNECTION_FAILURE';
